services:
  webserver:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - vpn

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    networks:
      - vpn

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    env_file:
      - .env
    hostname: $HOSTNAME
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    tty: true
    networks:
      - vpn
    restart: unless-stopped

networks:
  vpn:
    driver: bridge